#!/usr/bin/env bash
# this script extent previous exercise command, write a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# You cannot use pgrep
# shellcheck disable

./1-list_your_processes | grep "bash"
