#!/usr/bin/env bash
# this is script that displays To infinity and beyond indefinitely. 
# In between each iteration of the loop, will a sleep 2

while true; do
    echo "To infinity and beyond"
    sleep 2
done
