#!/usr/bin/env bash
# Display the contents of the current dircotory in life formate
# only display the part of the name after the first dash

list=$(ls)
for i in $list; do
       echo "$i" | cut -d'_' -f2
done
